# Generated by Django 5.1.15 on 2026-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#5b8cff', help_text='Color HEX de la columna en el Kanban.', max_length=7),
        ),
    ]
