# Generated by Django 5.1.15 on 2026-06-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado')], default='borrador', max_length=20)),
                ('generated_by', models.CharField(blank=True, help_text="Qué agente lo generó (ej. 'redactor'). Vacío si es manual.", max_length=50)),
                ('rationale', models.TextField(blank=True, help_text='Justificación del agente: por qué redactó así (trazabilidad).')),
                ('gmail_message_id', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pipeline.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
