# Generated by Django 5.1.15 on 2026-06-11 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_gmailaccount'),
        ('orgs', '0002_organization_coach_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(help_text='Ej: smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(help_text='Usuario SMTP (normalmente el email).', max_length=255)),
                ('password_enc', models.TextField()),
                ('from_email', models.EmailField(help_text='Dirección remitente.', max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS (puerto 587). Si es 465, usar SSL.')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GmailAccount',
        ),
    ]
