# Generated by Django 5.1.15 on 2026-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('objective', models.TextField(blank=True, help_text='Qué quiere lograr esta empresa con sus ventas.')),
                ('default_north_metric', models.CharField(choices=[('mails', 'Enviar más mails'), ('reuniones', 'Agendar más reuniones'), ('cierres', 'Concretar más negocios')], default='mails', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
