# Generated by Django 5.1.15 on 2026-06-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='coach_instructions',
            field=models.TextField(blank=True, help_text='Instrucciones que se inyectan al Coach para que sepa cómo ayudar a vender.'),
        ),
    ]
